services:
  dockeryt:
    pull_policy: never
    image: dockeryt
    container_name: dockeryt
    hostname: dockeryt
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    env_file:
      - ./env/.env
    depends_on:
      psql:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart # this depends on the project
          path: .
          target: /app

          ignore:
            - .venv/
            - __pycache__/

        - action: rebuild
          path: ./uv.lock

  ################################################################################

  psql:
    container_name: psql
    hostname: psql
    image: postgres:18
    restart: unless-stopped
    env_file:
      - ./env/.env
    volumes:
      - ./_data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
